spring:
  jpa:
    properties:
      hibernate.search.enabled: true
      hibernate.search.backend.type: lucene
      hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiHSearchAnalysisConfigurers$HapiLuceneAnalysisConfigurer
      hibernate.search.backend.directory.type: local-filesystem
      hibernate.search.backend.directory.root: /pvc-mount/prd/lucene.v8/
      hibernate.search.automatic_indexing.synchronization.strategy: read-sync
      hibernate.search.backend.lucene_version: lucene_current

fhir:
  server:
    security:
      issuer: https://auth-service.koppeltaal.headease.nl

smart:
  configuration:
    management_endpoint: https://domain-admin.koppeltaal.headease.nl
