spring:
  jpa:
    properties:
      hibernate.search.enabled: false

fhir:
  server:
    security:
      issuer: https://staging-auth-service.koppeltaal.headease.nl

smart:
  configuration:
    management_endpoint: https://staging-domain-admin.koppeltaal.headease.nl
