spring:
  jpa:
    properties:
      hibernate.search.backend.directory.root: /pvc-mount/prd/lucene/
      hibernate.search.automatic_indexing.synchronization.strategy: read-sync

fhir:
  server:
    security:
      issuer: https://auth-service.koppeltaal.headease.nl

smart:
  configuration:
    management_endpoint: https://domain-admin.koppeltaal.headease.nl
