service:
  internalPort: 8080
  externalPort: 8080

livenessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 50
#  initialDelaySeconds: 160 #enable when new npm profiles have to be loaded

readinessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 60
#  initialDelaySeconds: 180 #enable when new npm profiles have to be loaded
