service:
  internalPort: 8080
  externalPort: 8080
  type: LoadBalancer # expose service IP so that it can be whitelisted in firewalls for outbound Subscriptions

livenessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 60

readinessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 80
