global:
  hosts:
    externalIP: ${STATIC_IP}

service:
  internalPort: 8080
  externalPort: 8080

livenessProbe:
  path: /fhir/DEFAULT/.well-known/smart-configuration

readinessProbe:
  path: /fhir/DEFAULT/.well-known/smart-configuration

startupProbe:
  enabled: true
  path: /fhir/DEFAULT/.well-known/smart-configuration
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 90

# AD PV & PVC creation to mount Lucene db
persistence:
  enabled: true
  persistence:
    volumes[0].name: lucene-data
    volumes[0].claim.size: 1Gi
    volumes[0].mount.path: /data/lucene

strategyType: Recreate
