global:
  hosts:
    externalIP: ${STATIC_IP}

ingress:
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"

service:
  internalPort: 8080
  externalPort: 8080

livenessProbe:
  path: /fhir/DEFAULT/.well-known/smart-configuration
  initialDelaySeconds: 120
  timeoutSeconds: 30
  periodSeconds: 30
  failureThreshold: 5

readinessProbe:
  path: /fhir/DEFAULT/.well-known/smart-configuration
  initialDelaySeconds: 60
  timeoutSeconds: 15
  periodSeconds: 30
  failureThreshold: 10

startupProbe:
  enabled: true
  path: /fhir/DEFAULT/.well-known/smart-configuration
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 180

# AD PV & PVC creation to mount Lucene db
persistence:
  enabled: true
  persistence:
    volumes[0].name: lucene-data
    volumes[0].claim.size: 1Gi
    volumes[0].mount.path: /data/lucene

strategyType: Recreate

resources:
  requests:
    memory: 6G
  limits:
    memory: 10G

envVars:
  JAVA_OPTS: "-Xmx6g -Xms3g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ExitOnOutOfMemoryError"
