service:
  internalPort: 8080
  externalPort: 8080

livenessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 50
#  initialDelaySeconds: 160 #enable when new npm profiles have to be loaded

readinessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 60
#  initialDelaySeconds: 180 #enable when new npm profiles have to be loaded

# AD PV & PVC creation to mount Lucene db
extraVolumeMounts:
  - name: lucene-data
    persistentVolumeClaim:
      claimName: lucene-pvc

extraVolumes:
  - name: lucene-data
    persistentVolumeClaim:
      claimName: lucene-pvc

extraPersistentVolumeClaims:
  - metadata:
      name: lucene-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

extraPersistentVolumes:
  - metadata:
      name: lucene-pv
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 1Gi
      hostPath:
        path: /data/lucene
