service:
  internalPort: 8080
  externalPort: 8080

livenessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 60
  failureThreshold: 30

readinessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 80
  failureThreshold: 30
