service:
  internalPort: 8080
  externalPort: 8080

livenessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 50
#  initialDelaySeconds: 160 #enable when new npm profiles have to be loaded

readinessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 60
#  initialDelaySeconds: 180 #enable when new npm profiles have to be loaded

# Enable PV & PVC creation to mount Lucene db
persistence.enabled: true
persistence.volumes[0].claim.size: 1Gi
