service:
  internalPort: 8080
  externalPort: 8080

livenessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 80
#  initialDelaySeconds: 200 #enable when new npm profiles have to be loaded

readinessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 90
#  initialDelaySeconds: 200 #enable when new npm profiles have to be loaded

# AD PV & PVC creation to mount Lucene db
persistence:
  enabled: true
  persistence:
    volumes[0].name: lucene-data
    volumes[0].claim.size: 1Gi
    volumes[0].mount.path: /data/lucene

strategyType: Recreate
