service:
  internalPort: 8080
  externalPort: 8080

livenessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 30
#  initialDelaySeconds: 160 #enable when new npm profiles have to be loaded

readinessProbe:
  probeType: "tcpSocket"
  initialDelaySeconds: 40
#  initialDelaySeconds: 180 #enable when new npm profiles have to be loaded
