# .github/workflows/gitlab-mirror.yml
name: Mirror to GitLab

on:
  push:
    branches: [ '**' ]   # any branch
    tags:     [ '**' ]   # any tag
  delete:                # so branch/tag deletions propagate
    branches: [ '**' ]
    tags:     [ '**' ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      GITLAB_REMOTE: git@gitlab.com:headease/koppeltaal/kt2-hapi-server.git

    steps:
      - name: Check out *all* history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # required for a full mirror

      - name: Start SSH agent & load GitLab key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}

      - name: Add GitLab.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

      - name: Push branches & tags (force mirror)
        run: |
          # 1. ensure remote exists
          if git remote | grep -q '^gitlab$'; then
            git remote set-url gitlab "$GITLAB_REMOTE"
          else
            git remote add gitlab "$GITLAB_REMOTE"
          fi

          # 2. fetch all remote branches to ensure we have everything
          git fetch origin '+refs/heads/*:refs/heads/*'

          # 3. mirror branches, then tags; overwrite anything that differs
          git push --prune --force --all  gitlab
          git push --prune --force --tags gitlab
