# .github/workflows/gitlab-mirror.yml
# Mirrors **every** ref (branches, tags, deleted refs, Git LFS, etc.)
# from GitHub → GitLab keeping authors/committers intact.
name: Mirror to GitLab

on:
  push:
    branches: [ '**' ]   # any branch
    tags:     [ '**' ]   # any tag
  delete:                # so branch/tag deletions propagate
    branches: [ '**' ]
    tags:     [ '**' ]

jobs:
  mirror:
    runs-on: ubuntu-latest

    env:
      GITLAB_REMOTE: git@gitlab.com:headease/koppeltaal/kt2-hapi-server.git

    steps:
      - name: Check out *all* history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # required for a full mirror

      - name: Start SSH agent & load GitLab key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}

      - name: Add GitLab.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

      - name: Push branches & tags to GitLab
        run: |
          # create / update gitlab remote if needed
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab "$GITLAB_REMOTE"

          # mirror branches then tags (no hidden refs)
          git push --prune --force-with-lease --all  gitlab
          git push --prune --force-with-lease --tags gitlab
